config/routes.rb
Rails.application.routes.draw do
  resources :presses

  resources :authors

  resources :categories

  resources :products
  	
		    

end

app/controllers/presses_controller.rb
class PressesController < ApplicationController
  before_action :set_press, only: [:show, :edit, :update, :destroy]

  # GET /presses
  # GET /presses.json
  def index
    @presses = Press.all
  end

  # GET /presses/1
  # GET /presses/1.json
  def show
  	 @products_of_this_press = @press.products
  	 @products_for_thumbnail = @products_of_this_press.order(view: :desc).first(3)
  	 @products_for_media = @products_of_this_press.order(view: :desc).offset(3).limit(5)
  end

  # GET /presses/new
  def new
    @press = Press.new
  end

  # GET /presses/1/edit
  def edit
  end

  # POST /presses
  # POST /presses.json
  def create
    @press = Press.new(press_params)

    respond_to do |format|
      if @press.save
        format.html { redirect_to @press, notice: 'Press was successfully created.' }
        format.json { render :show, status: :created, location: @press }
      else
        format.html { render :new }
        format.json { render json: @press.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presses/1
  # PATCH/PUT /presses/1.json
  def update
    respond_to do |format|
      if @press.update(press_params)
        format.html { redirect_to @press, notice: 'Press was successfully updated.' }
        format.json { render :show, status: :ok, location: @press }
      else
        format.html { render :edit }
        format.json { render json: @press.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presses/1
  # DELETE /presses/1.json
  def destroy
    @press.destroy
    respond_to do |format|
      format.html { redirect_to presses_url, notice: 'Press was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_press
      @press = Press.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def press_params
      params.require(:press).permit(:name, :adress, :tel, :web)
    end
end

app/helpers/presses_helper.rb
module PressesHelper
end

app/views/presses/_form.html.erb
<%= form_for(@press) do |f| %>
  <% if @press.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@press.errors.count, "error") %> prohibited this press from being saved:</h2>

      <ul>
      <% @press.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presses/edit.html.erb
<h1>Editing Press</h1>

<%= render 'form' %>

<%= link_to 'Show', @press %> |
<%= link_to 'Back', presses_path %>

app/views/presses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Presses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Tel</th>
      <th>Web</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presses.each do |press| %>
      <tr>
        <td><%= press.name %></td>
        <td><%= press.adress %></td>
        <td><%= press.tel %></td>
        <td><%= press.web %></td>
        <td><%= link_to 'Show', press %></td>
        <td><%= link_to 'Edit', edit_press_path(press) %></td>
        <td><%= link_to 'Destroy', press, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Press', new_press_path %>

app/views/presses/new.html.erb
<h1>New Press</h1>

<%= render 'form' %>

<%= link_to 'Back', presses_path %>

app/views/presses/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'shared/topnav' %>
<p id="notice"><%= notice %></p>

<%= render 'shared/left' %>

<div class="col-md-6 column">
						
			<div class="row clearfix">
				<div class="page-header">
					<h3><%= @press.name %> </h3>
					</div>
				
				<!-IMAGE START>
				
				<div class="col-md-4 column">
					<img src="<%= @press.logo_url %>">
				</div>
				
				<!-IMAGE END>
				
				<div class="col-md-2 column"></div>
				<!- INFO START >
				<div class="col-md-6 column">
					<div class="well">
					<ul>

						<li>
							Adres: <strong><%= @press.adress %></strong>
						</li>
						<hr>
						<li>
							Tel: <strong><%= @press.tel %></strong>
						</li>
						<hr>
						<li>
							Veb: <strong>  <%= @press.web %></strong>
						</li>
						<hr>												
					</ul>
					</div>
				</div>
				<!-INFO END>
			</div>
			
			<div class="row clearfix"></div>
			<hr>
			<div class="row clearfix"> 
				<div class="col-md-12 column">
							<div class="row">
	<% @products_for_thumbnail.each do |pft|  %>			
				<div class="col-md-4">
					<div class="thumbnail">
						<img class="img-thumbnail" src="<%= pft.image_url %>" >
						<hr>
						<div class="caption">
						<p>
						<%= pft.author.name_with_initial %>
							</p>
							<hr>
							<p>
								<%= link_to "Bax", pft, :class => "btn btn-success" %> 
							</p>
						</div>
					</div>
				</div>
			<% end %>
			
			<div> 
			
			
			</div>
					
			 </div>
            
            			
				</div>
			</div>
		</div>

<%= render 'shared/right' %>
<%= render 'shared/footer' %>